services:
  atlas-core:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # ESTA ES LA LÍNEA MÁGICA. Le dice a Python: "La raíz de los imports es la carpeta /app del contenedor"
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload